#!/bin/bash

clang -O2 -emit-llvm -c $1.c -o - | llc -march=bpf -filetype=obj -o $1.o

# Need to replace the instructions as explained here: https://github.com/qmonnet/rbpf/blob/main/examples/load_elf.rs
# This feels sketchy but apparently the linux kernel does that as well.
xxd $1.o | sed ' s/6112 5000 0000 0000/7912 5000 0000 0000/ ;
    s/6111 4c00 0000 0000/7911 4000 0000 0000/ ;
   s/6111 2200 0000 0000/7911 2200 0000 0000/' | xxd -r > $1.tmp

mv $1.tmp $1.o


